### PR TITLE
add support for editing serverless regions

### PR DESCRIPTION
**Pull request by pjtatlow**
Because the openapi spec for editing serverless regions isn't in production yet, I manually copied this one from staging before running make. If we'd rather wait for it to be in production that would be okay though.

### CODE REVIEW

**Review by erademacher — COMMENTED** [review]
Any idea what's up with the .md whitespace diffs? It doesn't look like you touched any template files, and `generate-openapi-client` runs in docker, so I'm not sure what would cause them. Just extra white noise that makes changes like this harder to review.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-cloud-sdk-go/34#-:-NZ2-58l8Acn7kMCuXAM:b-fm7z6v)* status: 0 of 22 files reviewed, all discussions resolved

**Comment by pjtatlow** [comment]
> Any idea what's up with the .md whitespace diffs? It doesn't look like you touched any template files, and `generate-openapi-client` runs in docker, so I'm not sure what would cause them. Just extra white noise that makes changes like this harder to review.


@erademacher Yeah I'm not sure what caused that, does that not happen when you run it? 😅

**Review by erademacher — COMMENTED** [review]
Figured it out. Fixed with PR #35, which also pulls in the latest prod spec. Go ahead and rebase, please. Should result in a much smaller diff.

> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-cloud-sdk-go/34#-:-NZ2c6Wh8qg0kiHbDuMg:b4g5236)* status: 0 of 22 files reviewed, all discussions resolved

**Review by erademacher — APPROVED** [review]
:shipit: 
I'm not sure what's up with the new whitespace changes either, but they look fine and shouldn't be visible to users. I'll keep an eye out to see if they change back the next time someone updates the SDK.

> Reviewed 2 of 17 files at r2.
> *[Reviewable](https://reviewable.io/reviews/cockroachdb/cockroach-cloud-sdk-go/34#-:-N_0BPdeCuQ12rIqnRZl:beekyws)* status: 2 of 22 files reviewed, all discussions resolved

**Pull request merged**
